[package]
name = "poseidon-test"
version = "0.1.0"
edition = "2024"

[dependencies]
openzeppelin-crypto = { git = "https://github.com/OpenZeppelin/rust-contracts-stylus" }
num-bigint = "0.4.0"
num-traits = "0.2.19"
hex = "0.4.3"